spring:
  application:
    name: ${SPRINGBOOT_APP_NAME:eureka-registry}

server:
  port: ${EUREKA_REGISTRY_PORT:8761}

eureka:
  instance:
    hostname: ${spring.application.name:eureka-registry}
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


